# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import velo.advert.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (-1, 'Deleted')], default=0)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('location', models.SmallIntegerField(choices=[(10, 'TOP'), (20, 'Gallery'), (30, 'Gallery Side'), (40, 'News Side'), (50, 'Calendar Side')], default=10)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('kind', models.PositiveSmallIntegerField(choices=[(10, 'Show HTML'), (20, 'Show URL'), (30, 'Show Upload Img')], default=10)),
                ('converted', models.TextField(blank=True, help_text='Convert flash to html5 in https://www.google.com/doubleclick/studio/swiffy/')),
                ('banner_url', models.CharField(blank=True, help_text='If URL to banner is provided, then enter it here', max_length=200)),
                ('banner', models.ImageField(blank=True, help_text='If image banner is provided, upload it here', upload_to=velo.advert.models.get_banner_upload)),
                ('url', models.URLField(blank=True)),
                ('ordering', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0, editable=False)),
                ('click_count', models.IntegerField(default=0, editable=False)),
                ('show_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('show_end', models.DateTimeField(default=velo.advert.models._years_ahead)),
                ('language', models.CharField(blank=True, choices=[('', '*'), ('lv', 'Latvian'), ('en', 'English'), ('ru', 'Russian')], default='', max_length=10)),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
