# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_flashbanner_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashbanner',
            name='converted',
            field=models.TextField(blank=True, help_text='Convert flash to html5 in https://www.google.com/doubleclick/studio/swiffy/'),
        ),
        migrations.AlterField(
            model_name='flashbanner',
            name='location',
            field=models.CharField(choices=[('left-side', 'left-side')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flashbanner',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (-1, 'Deleted')], default=0),
        ),
    ]
