# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import velo.advert.models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_auto_20160408_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashbanner',
            name='banner_url',
            field=models.URLField(blank=True, help_text='If URL to banner is provided, then enter it here'),
        ),
        migrations.AddField(
            model_name='flashbanner',
            name='click_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='flashbanner',
            name='kind',
            field=models.PositiveSmallIntegerField(
                choices=[(10, 'Show HTML'), (20, 'Show URL'), (30, 'Show Upload Img')], default=10),
        ),
        migrations.AddField(
            model_name='flashbanner',
            name='show_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashbanner',
            name='show_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flashbanner',
            name='view_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='flashbanner',
            name='banner',
            field=models.ImageField(height_field='height', help_text='If image banner is provided, upload it here', upload_to=velo.advert.models.get_banner_upload, width_field='width'),
        ),
        migrations.AlterField(
            model_name='flashbanner',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='core.Competition'),
        ),
        migrations.AlterField(
            model_name='flashbanner',
            name='banner',
            field=models.ImageField(blank=True, height_field='height',
                                    help_text='If image banner is provided, upload it here',
                                    upload_to=velo.advert.models.get_banner_upload, width_field='width'),
        ),
        migrations.RemoveField(
            model_name='flashbanner',
            name='location',
        ),
        migrations.AddField(
            model_name='flashbanner',
            name='location',
            field=models.SmallIntegerField(
                choices=[(10, 'TOP'), (20, 'Gallery'), (30, 'Gallery Side'), (40, 'News Side'), (50, 'Calendar Side')],
                default=10),
        ),


    ]
