# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_auto_20160613_0005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashBanner',
            new_name='Banner',
        ),
    ]
