# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import velo.advert.models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20160613_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='show_end',
            field=models.DateTimeField(default=velo.advert.models._years_ahead),
        ),
    ]
