# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_auto_20160613_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='language',
            field=models.CharField(blank=True, choices=[('', '*'), ('lv', 'Latvian'), ('en', 'English'), ('ru', 'Russian')], default='', max_length=10),
        ),
    ]
