# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20160626_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ssn_hashed',
            field=models.CharField(blank=True, max_length=44, verbose_name='Social Security Number Hashed'),
        ),
    ]
