# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20150603_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(0, "Haven't Payed"), (10, 'Waiting for Payment'), (20, 'Payed'), (-10, 'Cancelled')], default=0, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (-1, 'Deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='number',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (-1, 'Deleted')], default=0),
        ),
    ]
