# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 15:20
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170126_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucicategory',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
