# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160408_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='can_send_newsletters',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
