# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-19 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20170826_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_shown_public',
            field=models.BooleanField(default=True, verbose_name='Is Shown Publicly'),
        ),
    ]
