# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20160415_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='UCICategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=60)),
                ('first_name', models.CharField(blank=True, max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='Last Name')),
                ('issued', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Birthday')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='can_send_newsletters',
            field=models.BooleanField(default=True, verbose_name='I want to receive velo.lv news in email.'),
        ),
    ]
