# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 01:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20160427_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
