# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-19 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_participant_is_shown_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='survey_answer1',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
