# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20160506_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='language',
            field=models.CharField(choices=[('lv', 'Latvian'), ('en', 'English'), ('ru', 'Russian')], default='lv', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
