# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-19 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_participant_survey_answer1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('distance', 'created'), 'verbose_name': 'participant', 'verbose_name_plural': 'participants'},
        ),
        migrations.AddField(
            model_name='participant',
            name='t_shirt_size',
            field=models.CharField(choices=[('XS', 'UNISEX XS'), ('S', 'UNISEX S'), ('M', 'UNISEX M'), ('L', 'UNISEX L'), ('XL', 'UNISEX XL'), ('XXL', 'UNISEX XXL')], max_length=3, null=True, verbose_name='T-Shirt size'),
        ),
        migrations.AlterField(
            model_name='application',
            name='can_send_newsletters',
            field=models.BooleanField(default=True, verbose_name='I want to receive velo.lv news in email.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_juridical_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Juridical Address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company name / Full Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_regnr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company number / SSN'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_vat',
            field=models.CharField(blank=True, max_length=100, verbose_name='VAT Number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition', verbose_name='Competition'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='application',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='application',
            name='external_invoice_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Invoice code'),
        ),
        migrations.AlterField(
            model_name='application',
            name='external_invoice_nr',
            field=models.CharField(blank=True, max_length=20, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='invoice_show_names',
            field=models.BooleanField(default=True, verbose_name='Show participant names in invoice'),
        ),
        migrations.AlterField(
            model_name='application',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(0, "Haven't Payed"), (10, 'Waiting for Payment'), (20, 'Payed'), (30, "Won't pay"), (-10, 'Cancelled')], default=0, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='email',
            field=models.EmailField(help_text='You will receive payment confirmation and information about start numbers.', max_length=254),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='bike_brand2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bike Brand'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='is_participating',
            field=models.BooleanField(default=False, verbose_name='Is Participating'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Result will be sent to this phone number', max_length=60, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='companyparticipant',
            name='ssn',
            field=models.CharField(blank=True, max_length=12, verbose_name='Social Security Number'),
        ),
        migrations.AlterField(
            model_name='number',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='number',
            name='group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='number',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='bike_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Choices', verbose_name='Bike Brand'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='bike_brand2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bike Brand'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Choices', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.CharField(blank=True, help_text='Assigned automatically', max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_competing',
            field=models.BooleanField(default=True, verbose_name='Is Competing'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_participating',
            field=models.BooleanField(default=False, verbose_name='Is Participating'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_paying',
            field=models.BooleanField(default=True, verbose_name='Is Paying'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Choices', verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Result will be sent to this phone number', max_length=60, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registration_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='send_email',
            field=models.BooleanField(default=True, verbose_name='Send Email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='send_sms',
            field=models.BooleanField(default=True, verbose_name='Send SMS'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ssn',
            field=models.CharField(blank=True, max_length=12, verbose_name='Social Security Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='where_heard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Choices', verbose_name='Where Heard'),
        ),
        migrations.AlterField(
            model_name='prenumberassign',
            name='group_together',
            field=models.SlugField(blank=True, help_text='Group together in one passage', null=True),
        ),
        migrations.AlterField(
            model_name='prenumberassign',
            name='number',
            field=models.IntegerField(blank=True, help_text='If specific number should be given', null=True),
        ),
        migrations.AlterField(
            model_name='prenumberassign',
            name='segment',
            field=models.IntegerField(blank=True, help_text='If specific passage should be given', null=True),
        ),
        migrations.AlterField(
            model_name='ucicategory',
            name='birthday',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='ucicategory',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='ucicategory',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Last Name'),
        ),
    ]
