# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-18 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181218_0905'),
        ('registration', '0007_auto_20180619_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparticipant',
            name='bike_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Choices', verbose_name='Velo Zīmols'),
        ),
    ]
