# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransactiontotals',
            name='date',
            field=models.DateField(),
        ),
    ]
