# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-27 12:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid
import velo.payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160710_0041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Company name / Full Name')),
                ('company_vat', models.CharField(blank=True, max_length=100, verbose_name='VAT Number')),
                ('company_regnr', models.CharField(blank=True, max_length=100, verbose_name='Company number / SSN')),
                ('company_address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('company_juridical_address', models.CharField(blank=True, max_length=100, verbose_name='Juridical Address')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('invoice_show_names', models.BooleanField(default=True, verbose_name='Show participant names in invoice')),
                ('slug', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('file', models.FileField(default='', upload_to=velo.payment.models.get_invoice_upload, verbose_name='Invoice URL')),
                ('series', models.CharField(blank=True, max_length=10, verbose_name='Competition series')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Series invoice number')),
                ('access_time', models.TimeField(blank=True, null=True)),
                ('access_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.PaymentChannel', verbose_name='Competition')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Competition', verbose_name='Competition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_invoice_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_invoice_set', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Payment', verbose_name='Payment')),
            ],
        ),
        migrations.AddField(
            model_name='paymentchannel',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('series', 'number')]),
        ),
    ]
