# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payment', '0002_auto_20170424_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Competition'),
        ),
    ]
