# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20150603_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'New'), (20, 'Pending'), (30, 'OK'), (-10, 'Reversed'), (-20, 'Cancelled'), (-30, 'Timeout'), (-40, 'Declined'), (-50, 'Failed'), (-60, 'Error'), (-70, 'ID not found')], default=10),
        ),
    ]
