# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-06 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_auto_20161227_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('code', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('status', models.SmallIntegerField(choices=[(-70, 'ID not found'), (-60, 'Error'), (-50, 'Failed'), (-40, 'Declined'), (-30, 'Timeout'), (-20, 'Cancelled'), (-10, 'Reversed'), (10, 'New'), (20, 'Pending'), (30, 'OK')], default=10)),
                ('external_code', models.CharField(blank=True, max_length=50)),
                ('external_code_requested', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Total amount')),
                ('information', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='LVL', max_length=10)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('server_response_at', models.DateTimeField(blank=True, null=True)),
                ('user_response_at', models.DateTimeField(blank=True, null=True)),
                ('server_response', models.TextField(blank=True)),
                ('user_response', models.TextField(blank=True)),
                ('returned_user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('returned_server_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('should_be_reviewed', models.BooleanField(default=False)),
                ('integration_id', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_transaction_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paymentchannel',
            name='cert_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),

        migrations.AddField(
            model_name='paymentchannel',
            name='key_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),

        migrations.AddField(
            model_name='paymentchannel',
            name='server_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentchannel',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.PaymentChannel'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_transaction_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Payment'),
        ),
    ]
