# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcampaign',
            name='discount_kind',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
