# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-21 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_discountcampaign_discount_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcampaign',
            name='discount_kind',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
