# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:03
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count, Max
from slugify import slugify

from velo.payment.models import Invoice
from django.db import connection


def set_sequences(apps, schema_editor):
    series = Invoice.objects.values('series').annotate(Count('series'), Max('number'))
    cursor = connection.cursor()
    for serie in series:
        sequence_name = "payment_sequence_%s" % slugify(serie.get('series'), only_ascii=True, ok="_")
        current = serie.get('number__max') + 1
        sql = 'CREATE SEQUENCE %s START %i;' % (sequence_name, current)
        print(sql)
        cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_dailytransactiontotals'),
        ('registration', '0005_application_external_invoice_to_local_invoice'),
        ('team', '0003_team_external_invoice_to_local_invoice'),
    ]

    operations = [
        migrations.RunPython(set_sequences),
    ]
