# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-25 17:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190121_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
