# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 07:44
from __future__ import unicode_literals

from django.db import migrations, connection


def migrate_data_back(apps, schema_editor):
    pass


def migrate_data(apps, schema_editor):
    cursor = connection.cursor()
    cursor.execute("Update gallery_album set folder='velo/'||folder")


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160408_2007'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrate_data_back),
    ]
