# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:11
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import easy_thumbnails.fields
import velo.team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
        ('core', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (-1, 'Deleted')], default=0)),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('slug', models.SlugField()),
                ('ssn', models.CharField(blank=True, max_length=12, verbose_name='SSN')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('license_nr', models.CharField(blank=True, max_length=50, verbose_name='License NR')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=velo.team.models.get_team_upload, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.SmallIntegerField(choices=[(10, 'Participant'), (20, 'Reserve')], db_index=True, verbose_name='Kind')),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Participant')),
                ('participant_potential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberapplication_potential_set', to='registration.Participant')),
                ('participant_unpaid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberapplication_unpaid_set', to='registration.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (-1, 'Deleted')], default=0)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('img', models.ImageField(blank=True, upload_to=velo.team.models.get_team_upload, verbose_name='Image')),
                ('shirt_image', models.ImageField(blank=True, upload_to=velo.team.models.get_team_upload, verbose_name='Shirt Image')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('management_info', models.TextField(blank=True, verbose_name='Management Info')),
                ('is_featured', models.BooleanField(default=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Company name / Full Name')),
                ('company_vat', models.CharField(blank=True, max_length=100, verbose_name='VAT Number')),
                ('company_regnr', models.CharField(blank=True, max_length=100, verbose_name='Company number / SSN')),
                ('company_address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('company_juridical_address', models.CharField(blank=True, max_length=100, verbose_name='Juridical Address')),
                ('external_invoice_code', models.CharField(blank=True, max_length=100, verbose_name='Invoice code')),
                ('external_invoice_nr', models.CharField(blank=True, max_length=20, verbose_name='Invoice Number')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_team_set', to=settings.AUTH_USER_MODEL)),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Distance')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_team_set', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('distance', '-is_featured', 'title'),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
