# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:43
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import easy_thumbnails.fields
import velo.team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
        ('core', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (-1, 'Deleted')], default=0)),
                ('first_name', models.CharField(max_length=60, verbose_name='Vārds')),
                ('last_name', models.CharField(max_length=60, verbose_name='Uzvārds')),
                ('birthday', models.DateField(verbose_name='Dzimšanas diena')),
                ('slug', models.SlugField()),
                ('ssn', models.CharField(blank=True, max_length=12, verbose_name='Personas kods')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Vīrietis'), ('F', 'Sieviete')], max_length=1, verbose_name='Dzimums')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Valsts')),
                ('license_nr', models.CharField(blank=True, max_length=50, verbose_name='Licences numurs')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=velo.team.models.get_team_upload, verbose_name='Attēls')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.SmallIntegerField(choices=[(10, 'Dalībnieks'), (20, 'Rezerve')], db_index=True, verbose_name='Tips')),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Participant')),
                ('participant_potential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberapplication_potential_set', to='registration.Participant')),
                ('participant_unpaid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberapplication_unpaid_set', to='registration.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Izveidots')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Labots')),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (-1, 'Deleted')], default=0)),
                ('title', models.CharField(max_length=100, verbose_name='Nosaukums')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('description', models.TextField(blank=True, verbose_name='Apraksts')),
                ('img', models.ImageField(blank=True, upload_to=velo.team.models.get_team_upload, verbose_name='Attēls')),
                ('shirt_image', models.ImageField(blank=True, upload_to=velo.team.models.get_team_upload, verbose_name='Krekla attēls')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Valsts')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Kontaktpersona')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-pasts')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Telefona numurs')),
                ('management_info', models.TextField(blank=True, verbose_name='Apkalpes informācija')),
                ('is_featured', models.BooleanField(default=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Uzņēmuma nosaukums / Vārds Uzvārds')),
                ('company_vat', models.CharField(blank=True, max_length=100, verbose_name='VAT Numurs')),
                ('company_regnr', models.CharField(blank=True, max_length=100, verbose_name='Uzņēmuma numurs / Personas kods')),
                ('company_address', models.CharField(blank=True, max_length=100, verbose_name='Adrese')),
                ('company_juridical_address', models.CharField(blank=True, max_length=100, verbose_name='Juridiskā adrese')),
                ('external_invoice_code', models.CharField(blank=True, max_length=100, verbose_name='Rēķina kods')),
                ('external_invoice_nr', models.CharField(blank=True, max_length=20, verbose_name='Rēķina numurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_team_set', to=settings.AUTH_USER_MODEL)),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Distance')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_team_set', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('distance', '-is_featured', 'title'),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
