# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-06 12:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django_countries.fields
import velo.team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_w',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='license_nr',
            field=models.CharField(blank=True, max_length=50, verbose_name='License NR'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.CharField(blank=True, max_length=12, verbose_name='SSN'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='kind',
            field=models.SmallIntegerField(choices=[(10, 'Participant'), (20, 'Reserve')], db_index=True, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_juridical_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Juridical Address'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company name / Full Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_regnr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company number / SSN'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_vat',
            field=models.CharField(blank=True, max_length=100, verbose_name='VAT Number'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='team',
            name='external_invoice_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Invoice code'),
        ),
        migrations.AlterField(
            model_name='team',
            name='external_invoice_nr',
            field=models.CharField(blank=True, max_length=20, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='team',
            name='management_info',
            field=models.TextField(blank=True, verbose_name='Management Info'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='team',
            name='shirt_image',
            field=models.ImageField(blank=True, upload_to=velo.team.models.get_team_upload, verbose_name='Shirt Image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
