# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180406_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_w',
            field=models.BooleanField(default=False, verbose_name='Women team'),
        ),
    ]
