# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 05:37
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import velo.team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20160408_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='legacy_id',
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=velo.team.models.get_team_upload, verbose_name='Image'),
        ),
    ]
