# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import velo.team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_show_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Uz šo telefona numuru tiks sūtīts rezultāts', max_length=60, verbose_name='Telefona numurs'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(verbose_name='Dzimšanas diena'),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Valsts'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Vārds'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Vīrietis'), ('F', 'Sieviete')], max_length=1, verbose_name='Dzimums'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Uzvārds'),
        ),
        migrations.AlterField(
            model_name='member',
            name='license_nr',
            field=models.CharField(blank=True, max_length=50, verbose_name='Licences numurs'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.CharField(blank=True, max_length=12, verbose_name='Personas kods'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='kind',
            field=models.SmallIntegerField(choices=[(10, 'Dalībnieks'), (20, 'Rezerve')], db_index=True, verbose_name='Tips'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Adrese'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_juridical_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Juridiskā adrese'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Uzņēmuma nosaukums / Vārds Uzvārds'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_regnr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Uzņēmuma numurs / Personas kods'),
        ),
        migrations.AlterField(
            model_name='team',
            name='company_vat',
            field=models.CharField(blank=True, max_length=100, verbose_name='VAT Numurs'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kontaktpersona'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Valsts'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Izveidots'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, verbose_name='Apraksts'),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-pasts'),
        ),
        migrations.AlterField(
            model_name='team',
            name='external_invoice_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rēķina kods'),
        ),
        migrations.AlterField(
            model_name='team',
            name='external_invoice_nr',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rēķina numurs'),
        ),
        migrations.AlterField(
            model_name='team',
            name='management_info',
            field=models.TextField(blank=True, verbose_name='Apkalpes informācija'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Labots'),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefona numurs'),
        ),
        migrations.AlterField(
            model_name='team',
            name='shirt_image',
            field=models.ImageField(blank=True, upload_to=velo.team.models.get_team_upload, verbose_name='Krekla attēls'),
        ),
        migrations.AlterField(
            model_name='team',
            name='show_contact_info',
            field=models.BooleanField(default=True, verbose_name='Rādīt kontaktinformāciju komandas profilā'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nosaukums'),
        ),
    ]
