FROM mdillon/postgis:9.6

RUN localedef -i lv_LV -c -f UTF-8 -A /usr/share/locale/locale.alias lv_LV.UTF-8
ENV LANG lv_LV.utf8

COPY ./initdb-dev.sh /docker-entrypoint-initdb.d/velo.sh
RUN chmod +x /docker-entrypoint-initdb.d/velo.sh
