# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=160)),
                ('is_processed', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
                ('send_out_at', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'permissions': (('can_update_marketing', 'Can update marketing'),),
            },
        ),
    ]
