# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_sms_discount_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'permissions': (('can_update_marketing', 'Can update marketing'),)},
        ),
    ]
