# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20150603_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailgunemail',
            name='em_replyto',
            field=models.CharField(default='pieteikumi@velo.lv', max_length=255),
        ),
    ]
