// Generated by CoffeeScript 1.10.0
(function() {
  var parseDate, show_hide_birthday, show_hide_ssn, teams, update_every_line;

  this.Member_inline_class_added = function(row) {
    return update_every_line(row);
  };

  this.Member_inline_class_removed = function(row) {
    return console.log('removed');
  };

  teams = null;

  parseDate = function(input) {
    var parts;
    parts = input.split('-');
    return new Date(parts[0], parts[1] - 1, parts[2]);
  };

  show_hide_ssn = function(parent_item, hide) {
    if (hide) {
      return $("input[name$='ssn']", parent_item).parents('.form-group').hide();
    } else {
      return $("input[name$='ssn']", parent_item).parents('.form-group').show();
    }
  };

  show_hide_birthday = function(parent_item, hide) {
    if (hide) {
      return $("input[name$='birthday']", parent_item).parents('.form-group').hide();
    } else {
      return $("input[name$='birthday']", parent_item).parents('.form-group').show();
    }
  };

  update_every_line = function(row) {
    $('.dateinput', row).datepicker({
      format: 'yyyy-mm-dd',
      autoclose: true,
      weekStart: 1
    });
    if ($("select[name$='country']", row).val() === 'LV') {
      maskedSSN($("input[name$='ssn']", row));
    }
    $("select[name$='country']", row).on('change', function(e) {
      var element, field, value;
      element = e.srcElement ? e.srcElement : e.target;
      element = $(element);
      value = element.val();
      if (value === 'LV') {
        return maskedSSN($("input[name$='ssn']", element.parents('.item')));
      } else {
        field = $("input[name$='ssn']", element.parents('.item'));
        field.unmask();
        return field.parents(".control-group").removeClass("error");
      }
    });
    if ($("select[name$='country']", row).val() === 'LV') {
      show_hide_ssn(row, false);
      show_hide_birthday(row, true);
    } else {
      show_hide_ssn(row, true);
      show_hide_birthday(row, false);
    }
    $("select[name$='country']", row).on('change', function(e) {
      var element;
      element = e.srcElement ? e.srcElement : e.target;
      if (element.value === 'LV') {
        show_hide_ssn(row, false);
        return show_hide_birthday(row, true);
      } else {
        show_hide_ssn(row, true);
        return show_hide_birthday(row, false);
      }
    });
    return "";
  };

  $(function() {
    var container, i, len, ref, results;
    ref = $('.item:not(.template)');
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      container = ref[i];
      results.push(update_every_line($(container)));
    }
    return results;
  });

}).call(this);

//# sourceMappingURL=team_form.js.map
