# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='term_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='term_lv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='term_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
