# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-19 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import easy_thumbnails.fields
import velo.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170809_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='description_lv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
