# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:07
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.manager
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160407_1419'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='competition',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_validation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_validation_expiry',
        ),
        migrations.AlterField(
            model_name='choices',
            name='kind',
            field=models.SmallIntegerField(choices=[(10, 'Bike Brand'), (20, 'Occupation'), (30, 'Where Heard'), (40, 'City')]),
        ),
        migrations.AlterField(
            model_name='competition',
            name='alias',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='bill_series',
            field=models.CharField(blank=True, default='B', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='kind',
            field=models.SmallIntegerField(choices=[(0, 'Velo'), (1, 'Cross Country')], default=0),
        ),
        migrations.AlterField(
            model_name='competition',
            name='payment_channel',
            field=models.CharField(default='LKDF', max_length=20),
        ),
        migrations.AlterField(
            model_name='distance',
            name='distance_m',
            field=models.IntegerField(blank=True, help_text='Distance in meters', null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (-1, 'Deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='LV', max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_status',
            field=models.SmallIntegerField(choices=[(10, 'Not yet validated'), (20, 'Bounced'), (40, 'Validating'), (50, 'Valid'), (-10, 'Invalid')], default=10),
        ),
    ]
