# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models, connection


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_competition_logo_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_lv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='name_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
