# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models, connection
from sitetree.models import TreeItem

import velo.core.models


def migrate_data_back(apps, schema_editor):
    pass


def migrate_data(apps, schema_editor):
    cursor = connection.cursor()

    cursor.execute("Update core_competition set name_lv=name")

    # SEB
    velo.core.models.Competition.objects.filter(id=51).update(name_en="SEB MTB Marathon 2016",
                                                              name_ru="SEB MTB марафон 2016")
    velo.core.models.Competition.objects.filter(id=38).update(name_en="SEB MTB Marathon 2015",
                                                              name_ru="SEB MTB марафон 2015")
    velo.core.models.Competition.objects.filter(id=25).update(name_en="SEB MTB Marathon 2014",
                                                              name_ru="SEB MTB марафон 2014")
    velo.core.models.Competition.objects.filter(id=17).update(name_en="SEB MTB Marathon 2013",
                                                              name_ru="SEB MTB марафон 2013")
    velo.core.models.Competition.objects.filter(id=2).update(name_en="SEB MTB Marathon 2012",
                                                             name_ru="SEB MTB марафон 2012")
    velo.core.models.Competition.objects.filter(id=1).update(name_en="SEB MTB Marathon", name_ru="SEB MTB марафон")

    velo.core.models.Competition.objects.filter(id__in=[3, 18, 26, 39, 52]).update(name_en="1st Stage",
                                                                                   name_ru="1-й этап")
    velo.core.models.Competition.objects.filter(id__in=[4, 19, 27, 40, 53]).update(name_en="2nd Stage",
                                                                                   name_ru="2-й этап")
    velo.core.models.Competition.objects.filter(id__in=[5, 20, 28, 41]).update(name_en="3rd Stage", name_ru="3-й этап")
    velo.core.models.Competition.objects.filter(id__in=[54, ]).update(name_en="UEC & 3rd Stage",
                                                                      name_ru="UEC & 3-й этап")
    velo.core.models.Competition.objects.filter(id__in=[6, 21, 29, 42, 55]).update(name_en="4th Stage",
                                                                                   name_ru="4-й этап")
    velo.core.models.Competition.objects.filter(id__in=[7, 22, 30, 43, 56]).update(name_en="5th Stage",
                                                                                   name_ru="5-й этап")
    velo.core.models.Competition.objects.filter(id__in=[8, 23, 31, 44, 57]).update(name_en="6th Stage",
                                                                                   name_ru="6-й этап")
    velo.core.models.Competition.objects.filter(id__in=[32, 45, 58]).update(name_en="7th Stage", name_ru="7-й этап")

    # Vienibas
    velo.core.models.Competition.objects.filter(id__in=[13, ]).update(name_en="Latvian Cyclists Unity Ride",
                                                                      name_ru="Велопробег Единства")
    velo.core.models.Competition.objects.filter(id__in=[15, ]).update(name_en="Latvian Cyclists Unity Ride 2012",
                                                                      name_ru="Велопробег Единства 2012")
    velo.core.models.Competition.objects.filter(id__in=[16, ]).update(name_en="Latvian Cyclists Unity Ride 2013",
                                                                      name_ru="Велопробег Единства 2013")
    velo.core.models.Competition.objects.filter(id__in=[35, ]).update(name_en="Latvian Cyclists Unity Ride 2014",
                                                                      name_ru="Велопробег Единства 2014")
    velo.core.models.Competition.objects.filter(id__in=[48, ]).update(name_en="Latvian Cyclists Unity Ride 2015",
                                                                      name_ru="Велопробег Единства 2015")
    velo.core.models.Competition.objects.filter(id__in=[62, ]).update(name_en="Latvian Cyclists Unity Ride 2016",
                                                                      name_ru="Велопробег Единства 2016")

    # Rigas
    velo.core.models.Competition.objects.filter(id__in=[9, ]).update(name_en="Riga Cycling Marathon",
                                                                     name_ru="Рижский Веломарафон")
    velo.core.models.Competition.objects.filter(id__in=[10, ]).update(name_en="TELE2 Riga Cycling Marathon 2012",
                                                                      name_ru="TELE2 Рижский Веломарафон 2012")
    velo.core.models.Competition.objects.filter(id__in=[11, ]).update(name_en="TELE2 Riga Cycling Marathon 2013",
                                                                      name_ru="TELE2 Рижский Веломарафон 2013")
    velo.core.models.Competition.objects.filter(id__in=[34, ]).update(name_en="Riga Cycling Marathon 2014",
                                                                      name_ru="Рижский Веломарафон 2014")
    velo.core.models.Competition.objects.filter(id__in=[47, ]).update(name_en="ELKOR Riga Cycling Marathon 2015",
                                                                      name_ru="ELKOR Рижский Веломарафон 2015")
    velo.core.models.Competition.objects.filter(id__in=[61, ]).update(name_en="Riga Cycling Marathon 2016",
                                                                      name_ru="Рижский Веломарафон 2016")

    # Rigas Mini
    velo.core.models.Competition.objects.filter(id__in=[12, ]).update(name_en="Riga Children Mini Cycling Marathon",
                                                                      name_ru="Детский мини веломарафон")
    velo.core.models.Competition.objects.filter(id__in=[14, ]).update(
        name_en="Riga Children Mini Cycling Marathon 2012", name_ru="Детский мини веломарафон 2012")
    velo.core.models.Competition.objects.filter(id__in=[24, ]).update(name_en="SPICE Mini Cycling Marathon 2013",
                                                                      name_ru="Детский мини веломарафон Spice 2013")
    velo.core.models.Competition.objects.filter(id__in=[33, ]).update(
        name_en="Riga Children Mini Cycling Marathon 2014", name_ru="Детский мини веломарафон 2014")
    velo.core.models.Competition.objects.filter(id__in=[46, ]).update(
        name_en="Riga Children Mini Cycling Marathon 2015", name_ru="Детский мини веломарафон 2015")
    velo.core.models.Competition.objects.filter(id__in=[60, ]).update(
        name_en="Riga Children Mini Cycling Marathon 2016", name_ru="Детский мини веломарафон 2016")

    # Baltijas
    velo.core.models.Competition.objects.filter(id__in=[36, ]).update(name_en="Baltics Bike Tour 'Baltic Chain'",
                                                                      name_ru="Велопробег Балтийского пути")
    velo.core.models.Competition.objects.filter(id__in=[37, ]).update(name_en="Baltics Bike Tour 'Baltic Chain' 2014",
                                                                      name_ru="Велопробег Балтийского пути 2014")
    velo.core.models.Competition.objects.filter(id__in=[49, ]).update(name_en="Baltics Bike Tour 'Baltic Chain' 2015",
                                                                      name_ru="Велопробег Балтийского пути 2015")

    velo.core.models.Competition.objects.filter(id__in=[51, 52, 53, 54, 55, 56, 57, 58]).update(
        description_lv="SEB MTB jau ilgus gadus ir lielākais un populārākais sporta sacensību seriāls Latvijā.",
        description_ru="SEB MTB в течение многих лет является самым крупным и наиболее популярная серия спортивного соревнования в Латвии.",
        description_en="SEB MTB for many years is the largest and most popular sporting competition series in Latvia.")

    velo.core.models.Competition.objects.filter(id__in=[60, 61, 62]).update(
        description_lv="Lorem ipsum dolor sit amet, eos at hinc nostro deterruisset. Id natum complectitur intellegebat eos. Verterem nominati ut quo, pro vide oratio ut. Clita voluptatum ullamcorper mel ex.",
        description_ru="Lorem ipsum dolor sit amet, eos at hinc nostro deterruisset. Id natum complectitur intellegebat eos. Verterem nominati ut quo, pro vide oratio ut. Clita voluptatum ullamcorper mel ex.",
        description_en="Lorem ipsum dolor sit amet, eos at hinc nostro deterruisset. Id natum complectitur intellegebat eos. Verterem nominati ut quo, pro vide oratio ut. Clita voluptatum ullamcorper mel ex.")


    TreeItem.objects.get(id=54).delete()
    TreeItem.objects.get(id=59).delete()

    prof = TreeItem.objects.get(id=52)
    prof.inmenu = False
    prof.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20160414_2109'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrate_data_back),
    ]
