# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import velo.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='gpx',
            field=models.FileField(blank=True, null=True, upload_to=velo.core.models._get_gpx_upload_path),
        ),
        migrations.AlterField(
            model_name='distance',
            name='kind',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
