# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import velo.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160427_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=velo.core.models._get_profile_upload_path, verbose_name='Profile Image'),
        ),
    ]
