# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legacy_id',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
