# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 08:01
from __future__ import unicode_literals

from django.db import migrations, models, connection
import easy_thumbnails.fields
import velo.core.models




def migrate_data_back(apps, schema_editor):
    pass


def migrate_data(apps, schema_editor):
    cursor = connection.cursor()

    cursor.execute("Update core_distance set name_lv=name")
    cursor.execute("Update core_distance set name_en=name")
    cursor.execute("Update core_distance set name_ru=name")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160428_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distance',
            name='name_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distance',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=velo.core.models._get_profile_upload_path, verbose_name='Profile Image'),
        ),
        migrations.RunPython(migrate_data, migrate_data_back),
    ]
