# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator('^[-\\w/\\.~]+$', 'Šī vērtība var saturēt tikai burtus, numurus, punktus, zemsvītras, svītras, tildes.')], verbose_name='Adrese')),
                ('title', models.CharField(max_length=200, verbose_name='nosaukums')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='saturs')),
                ('content_md', markdownx.models.MarkdownxField(blank=True)),
                ('enable_comments', models.BooleanField(default=False, verbose_name='pieslēgt komentārus')),
                ('ordering', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('language', models.CharField(blank=True, choices=[('', '*'), ('lv', 'Latvian'), ('en', 'English'), ('ru', 'Russian')], default='', max_length=10)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
            options={
                'verbose_name': 'statiskā lapa',
                'verbose_name_plural': 'statiskā lapa',
                'ordering': ('competition', 'ordering'),
            },
        ),
    ]
