# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpage', '0002_auto_20150819_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='language',
            field=models.CharField(blank=True, choices=[('', '*'), ('lv', 'Latvian'), ('en', 'English')], default='', max_length=10),
        ),
    ]
