# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 21:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpage', '0003_auto_20160408_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='language',
            field=models.CharField(blank=True, choices=[('', '*'), ('lv', 'Latvian'), ('en', 'English'), ('ru', 'Russian')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='url',
            field=models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator('^[-\\w/\\.~]+$', 'This value must contain only letters, numbers, dots, underscores, dashes, slashes or tildes.')], verbose_name='URL'),
        ),
    ]
