# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 10:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpage', '0005_staticpage_content_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content'),
        ),
    ]
