# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import velo.supporter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSupporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_title', models.CharField(blank=True, max_length=100)),
                ('support_title_lv', models.CharField(blank=True, max_length=100, null=True)),
                ('support_title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('support_title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('is_large_logo', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=1000)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_logo', models.FileField(blank=True, upload_to=velo.supporter.models._get_logo_upload_path)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, height_field='height', upload_to=velo.supporter.models._get_logo_upload_path, width_field='width')),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('is_agency_supporter', models.BooleanField(default=False)),
                ('default_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='supporter.Logo')),
                ('default_svg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='supporter.Logo')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='logo',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporter.Supporter'),
        ),
        migrations.AddField(
            model_name='competitionsupporter',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supporter.Logo'),
        ),
        migrations.AddField(
            model_name='competitionsupporter',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporter.Supporter'),
        ),
    ]
