# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0002_auto_20160719_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionsupporter',
            name='support_level',
        ),
    ]
