# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import velo.supporter.models


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0002_auto_20160408_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='svg_logo',
            field=models.FileField(blank=True, upload_to=velo.supporter.models._get_logo_upload_path),
        ),
    ]
