# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('supporter', '0003_logo_svg_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='default_svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='supporter.Logo'),
        ),

    ]
